### ISSUE TITLE
Figure out why POST is not working

### ISSUE THREAD

**Issue by sithstalker340** [nns3455/SWEN-344-API#11]

**Comment by AlexanderKidd** [comment]
What We Know:
- POST seems to have broken from R1 to R2 on both Personal SE and VM accounts: So it is probably a flaw in our code.
- GET requests work fine: from the request to accessing the database to the response
- With basic PHP echo debugging, it appears the code breaks at `$result = $query->execute();`
- INSERT statement appears to be completely valid.
- **addClassroom appears to work on our Personal SE APIs.  🥇 Solution was to change permissions to directory 777.**

Possible Troublshooting:
- Allow rwx permissions on entire API folder.
- Test on local machine (literally everything on your Desktop, same directory level).
- Run PHP SQL code in another environment (like CodingGrounds online PHP compiler).
- Check R1 code.  **Probably should be done first for further information.**
  - **Edit: The only real change to the POST functions was returning the last inserted row rather than the $result object.  This shouldn't affect the problem since the code appears to break when executing the SQL statement before this return statement.**

**Comment by AlexanderKidd** [comment]
@mcd4874 and I were able to get this working last Saturday on our accounts.  It was a permissions error.  I'll leave this up until @axv3658 figures it out.
